export const P_TEN = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec laoreet augue. Praesent sit amet viverra sem. Donec ultrices mollis aliquam. Vivamus aliquam consequat quam. Sed luctus feugiat risus, eget fermentum erat pharetra ut. Proin orci lectus, commodo sed condimentum eget, interdum a augue. Cras eu posuere augue, eget elementum metus. Vivamus vitae dapibus tellus, in mattis quam. Vestibulum ultrices pellentesque dapibus.

Aenean scelerisque est eu consectetur luctus. Curabitur ornare, erat ut porta dapibus, ex leo sagittis odio, ultrices ullamcorper magna enim a lacus. Curabitur posuere faucibus orci, vitae ultricies est auctor quis. Integer at lacinia purus. Curabitur tempus commodo neque. Maecenas et euismod massa. Vestibulum nec iaculis justo. Donec vel consequat mi. Nulla facilisi. Suspendisse eu vestibulum ex. Donec at eleifend nisi. Nunc varius, ex at efficitur ultrices, lorem sem iaculis massa, eget consequat nunc justo id eros.

Aenean dignissim risus velit, in pharetra lectus varius a. Nunc nec lorem et arcu eleifend elementum. Sed quis augue sollicitudin, suscipit ligula in, mattis mauris. Nulla consequat finibus turpis ac sodales. Quisque massa nisi, blandit quis venenatis id, sagittis vitae nunc. Phasellus fermentum pulvinar tincidunt. Ut cursus enim a quam tincidunt fringilla eget at felis. Nam ut mauris tellus. Nunc a congue nisl. Phasellus maximus accumsan lectus, eu porta arcu interdum id.

Integer quis laoreet ex, eget interdum dui. Mauris nec ex in dolor pharetra convallis. Nunc in mauris sit amet lorem interdum venenatis. Nam sit amet lacinia leo. Aliquam faucibus nisl sit amet urna pellentesque rhoncus. Vestibulum feugiat leo sed dignissim suscipit. Nam id ullamcorper diam. Nulla iaculis dapibus dui, malesuada volutpat magna sollicitudin eu. Duis ut turpis vel nibh posuere finibus a non lectus. Nam sed tellus odio. Phasellus sem justo, aliquam lobortis lacus in, malesuada tincidunt mauris. Etiam sed risus luctus, eleifend nisi eu, rutrum odio. Morbi rhoncus est id tortor cursus blandit.

Praesent non arcu at elit tincidunt rutrum in at metus. Fusce interdum, justo a aliquet finibus, quam libero fermentum tortor, in molestie elit eros sed neque. Nullam varius consequat dolor, ornare egestas tellus fermentum id. Pellentesque vitae ipsum a dolor viverra accumsan eu eu orci. Aliquam luctus orci ac iaculis ultrices. In ullamcorper erat vel risus faucibus, id euismod libero ultrices. Vivamus vehicula lacinia nibh, a scelerisque magna. Nullam venenatis risus erat, commodo mattis lacus consectetur non. Duis lacus odio, aliquam id cursus nec, commodo at tellus. Aliquam convallis feugiat ante, id volutpat ligula maximus vitae. Fusce vestibulum cursus sodales. Cras pellentesque in lacus sit amet rhoncus. Suspendisse ac elit eget nibh accumsan cursus.

Nulla consequat ornare ligula, non fringilla odio rutrum accumsan. Fusce congue est a diam mollis, sed malesuada sapien sagittis. Vestibulum ornare ullamcorper dui, a suscipit sapien scelerisque sed. Proin congue accumsan ultrices. In eu malesuada nisi. Quisque sit amet pharetra metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris ornare pharetra purus, eu tincidunt diam aliquet non. Ut ut ante et odio ultrices tincidunt in eu nisi. Aliquam vel ex eros. Morbi auctor eleifend massa vel pellentesque.

Nullam semper hendrerit tellus, et congue ante fringilla ac. Aenean tristique euismod malesuada. Vestibulum porta, nibh eget congue malesuada, dui est tempus ante, vitae porta metus ipsum ut sapien. Proin nibh justo, condimentum non erat nec, sodales commodo nunc. Curabitur vehicula odio non ex condimentum malesuada. Fusce iaculis tempor eros, vel volutpat magna cursus in. Etiam tincidunt massa ligula, vel auctor arcu hendrerit sed. Fusce gravida orci eu orci bibendum interdum. Etiam scelerisque sollicitudin fringilla. Curabitur ut nisl iaculis velit ullamcorper cursus. Nullam dignissim feugiat libero, et finibus diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer lacus quam, volutpat eget volutpat eget, lacinia sit amet dui. Nulla ut ante id ipsum ultricies dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Nam interdum ante sapien, quis consectetur ligula viverra non. Mauris commodo libero maximus, molestie quam non, bibendum dolor. Mauris nulla orci, vehicula sit amet consequat in, pretium sed mauris. Maecenas interdum diam non ipsum volutpat, ut rutrum nunc eleifend. Nulla suscipit, massa et feugiat molestie, diam enim fringilla ex, id rutrum orci neque elementum augue. Phasellus a leo vitae ligula varius porta eu in lorem. Ut sed vehicula nunc. Duis nec felis sapien.

Vestibulum eu lacus odio. Vestibulum finibus varius consequat. Sed consectetur luctus neque quis ullamcorper. Curabitur pretium tempor ultricies. Donec a purus tortor. Suspendisse id ex non massa feugiat viverra eget sit amet ante. Nam vehicula sapien non lorem molestie, vel feugiat ex rutrum. Sed hendrerit sit amet justo non mollis.

Proin ullamcorper felis et risus convallis, et blandit mauris malesuada. Nullam sit amet malesuada eros, non egestas erat. Nulla pharetra urna massa, id interdum odio iaculis non. Duis imperdiet dolor eu turpis tristique, ut maximus urna vestibulum. Ut sit amet augue pharetra, feugiat mi ultricies, aliquet eros. Ut vel dui eu est fermentum sollicitudin. Phasellus molestie dignissim aliquam. In mattis augue id sapien placerat, sit amet molestie tellus interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse feugiat elit in sodales blandit. In lobortis lorem et lacus tempor tincidunt. Pellentesque in luctus libero, sed viverra augue. Nulla eget mi felis. Morbi hendrerit velit a lectus lacinia, non euismod quam rhoncus. Nam dictum odio velit, a tincidunt augue iaculis nec. Aliquam dui diam, faucibus in imperdiet eu, lobortis consectetur metus.`;
